parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: news
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 6eee3fc2e14d7179d0db75cb7a57e1a6c071b5aa
