<?php
namespace Acme\NewsBundle\Entity\News;

use Doctrine\ORM\EntityRepository;

/**
 * Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends EntityRepository
{
    /**
     * @param $page
     * @param $perPage
     * @return array
     */
    public function getAllByPage($page, $perPage)
    {
        $offset = $perPage * ($page - 1);
        $limit = $perPage;

        return $this->createQueryBuilder('n')
            ->where('n.isPublished = (?1)')
            ->setParameter(1, 1)
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $queryBuilder;
    }

    /**
     * @param $id
     * @param int $limit
     * @return array
     */
    public function getRelatedNewsById($id, $limit = 3)
    {
        return $this->createQueryBuilder('n')
            ->where('n.id != (?1)')
            ->andWhere('n.isPublished = (?2)')
            ->setParameter(1, $id)
            ->setParameter(2, 1)
            ->orderBy('n.date', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
